import PostProvider from '@/context/PostProvider'
import './globals.css'
import type { Metadata } from 'next'
import {  Roboto } from 'next/font/google'

const roboto = Roboto({ 
  subsets: ['latin'],
  weight: ['400', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} md:mx-32 sm:mx-20 `}>
        <PostProvider>
          {children}
        </PostProvider>
      </body>
    </html>
  )
}
